import Head from 'next/head'
import { Layout } from '../components/Layout'

export default function Home() {
  return (
    <Layout>
      <Head>
        <title>Home | Standing Dreams</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </Layout>
  )
}
